### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by nilrodes** [UNISvalbard/Geo-MOD#2]
- [x] Define learning outcomes "...\Geo-MOD\content\lessons\intro\intro.md"
- [x] Design certificate evaluation @PeterBetlem "...\Geo-MOD\content\certification.md"
- [x] Design final exercise (own data processing + data integration in GIS): "...\Geo-MOD\content\lessons\data_process\data_process.md"
